import { useGrazingSessionMapController } from '@/components/maps/hooks/use-grazing-session-map-controller'
import { useGeolocationWatcher } from '@/components/maps/hooks/use-geolocation-watcher'
import { useGrazingSessionMapPresentation } from '@/components/maps/hooks/use-grazing-session-map-presentation'
import type { GrazingSessionMapScreenData } from '@/components/maps/hooks/use-grazing-session-map-screen-data'
import type { GrazingSessionMapState } from '@/components/maps/hooks/use-grazing-session-map-state'

type UseGrazingSessionMapScreenControllerOptions = {
  state: GrazingSessionMapState
  screenData: GrazingSessionMapScreenData
}

export function useGrazingSessionMapScreenController({
  state,
  screenData,
}: UseGrazingSessionMapScreenControllerOptions) {
  const { refs, gps, selection, session, edit, history } = state
  const { data, runtime, effectiveSettings, settingsRef, buildPositionRef } = screenData

  const controller = useGrazingSessionMapController({
    activeSession: data.activeSession ?? null,
    selectedSession: data.selectedSession,
    groupedSessionHistory: data.groupedSessionHistory,
    safeCurrentTrackpoints: data.safeCurrentTrackpoints,
    safeSelectedTrackpoints: data.safeSelectedTrackpoints,
    safeHerds: data.safeHerds,
    animalsByHerdId: data.animalsByHerdId,
    acceptedPositionRef: refs.acceptedPositionRef,
    selectedHerdId: session.selectedHerdId,
    sessionAnimalCount: session.sessionAnimalCount,
    sessionNotes: session.sessionNotes,
    selectedSessionId: selection.selectedSessionId,
    editingSessionId: edit.editingSessionId,
    editTrackpoints: edit.editTrackpoints,
    editStartTime: edit.editStartTime,
    editEndTime: edit.editEndTime,
    selectedEditTrackpointIndex: edit.selectedEditTrackpointIndex,
    setSelectedHerdId: session.setSelectedHerdId,
    setSessionAnimalCount: session.setSessionAnimalCount,
    setSessionNotes: session.setSessionNotes,
    setCurrentSessionId: session.setCurrentSessionId,
    setCurrentSessionStatus: session.setCurrentSessionStatus,
    setSelectedSessionId: selection.setSelectedSessionId,
    setEditingSessionId: edit.setEditingSessionId,
    setEditTrackpoints: edit.setEditTrackpoints,
    setEditStartTime: edit.setEditStartTime,
    setEditEndTime: edit.setEditEndTime,
    setSelectedEditTrackpointIndex: edit.setSelectedEditTrackpointIndex,
    setIsAddingEditTrackpoint: edit.setIsAddingEditTrackpoint,
    setActionError: session.setActionError,
    setIsSaving: session.setIsSaving,
    setIsEventSaving: session.setIsEventSaving,
    setEventNote: session.setEventNote,
    setEventStatus: session.setEventStatus,
    setExpandedHistoryDays: history.setExpandedHistoryDays,
    setExpandedHistorySessionId: history.setExpandedHistorySessionId,
    setLiveDurationTick: session.setLiveDurationTick,
  })

  useGeolocationWatcher({
    acceptedPositionRef: refs.acceptedPositionRef,
    buildPositionRef,
    onAcceptedPositionRef: controller.handleAcceptedPositionRef,
    settingsRef,
    watchIdRef: refs.watchIdRef,
    setGpsState: gps.setGpsState,
    setLastPositionDecision: gps.setLastPositionDecision,
    setPosition: gps.setPosition,
  })

  const presentation = useGrazingSessionMapPresentation({
    gpsState: gps.gpsState,
    position: gps.position,
    lastPositionDecision: gps.lastPositionDecision,
    effectiveSettings,
    safeHerds: data.safeHerds,
    selectedHerdId: session.selectedHerdId,
    currentSessionStatus: session.currentSessionStatus,
  })

  return {
    liveStatusCardProps: {
      gpsState: gps.gpsState,
      gpsLabel: presentation.gpsLabel,
      gpsDetail: presentation.gpsDetail,
      gpsFilterDetail: presentation.gpsFilterDetail,
      herdLabel: presentation.herdLabel,
      statusLabel: presentation.statusLabel,
      coordinatesLabel: presentation.coordinatesLabel,
      updateLabel: presentation.updateLabel,
      isOpen: gps.isLiveStatusOpen,
      onToggleOpen: () => gps.setIsLiveStatusOpen((current) => !current),
    },
    canvasPanelProps: {
      containerRef: runtime.containerRef,
      editingSessionId: edit.editingSessionId,
      safeCurrentTrackpointsLength: data.safeCurrentTrackpoints.length,
      currentDistanceM: data.currentMetrics?.distanceM ?? 0,
      currentDurationS: data.currentMetrics?.durationS ?? 0,
      safeHerds: data.safeHerds,
      selectedHerdId: session.selectedHerdId,
      selectedAnimalCount: session.sessionAnimalCount,
      sessionNotes: session.sessionNotes,
      currentSessionStatus: session.currentSessionStatus,
      isSaving: session.isSaving,
      isEventSaving: session.isEventSaving,
      hasHerds: data.safeHerds.length > 0,
      eventNote: session.eventNote,
      eventStatus: session.eventStatus,
      actionError: session.actionError,
      currentMetrics: data.currentMetrics,
      safeCurrentSessionEvents: data.safeCurrentSessionEvents,
      position: gps.position,
      isBaseLayerMenuOpen: runtime.isBaseLayerMenuOpen,
      baseLayer: runtime.baseLayer,
      showSurveyAreas: runtime.showSurveyAreas,
      showSessionEventsOnMap: runtime.showSessionEventsOnMap,
      prefetchingMapArea: runtime.prefetchingMapArea,
      prefetchStatus: runtime.prefetchStatus,
      isAddingEditTrackpoint: edit.isAddingEditTrackpoint,
      selectedEditTrackpointIndex: edit.selectedEditTrackpointIndex,
      editTrackpointsLength: edit.editTrackpoints.length,
      onSelectedHerdIdChange: controller.changeSelectedHerdId,
      onAdjustAnimalCount: controller.adjustSessionAnimalCount,
      onSessionNotesChange: session.setSessionNotes,
      onStartOrResumeSession:
        session.currentSessionStatus === 'paused'
          ? controller.resumeSession
          : controller.startSession,
      onPauseSession: controller.pauseSession,
      onResumeSession: controller.resumeSession,
      onStopSession: controller.stopSession,
      onEventNoteChange: session.setEventNote,
      onAddSessionMarkerEvent: controller.addSessionMarkerEvent,
      onCenterMap: runtime.centerMapOnPosition,
      onToggleBaseLayerMenu: () => runtime.setIsBaseLayerMenuOpen((current) => !current),
      onUpdateBaseLayer: runtime.updateBaseLayer,
      onToggleShowSurveyAreas: () => runtime.setShowSurveyAreas((current) => !current),
      onToggleShowSessionEventsOnMap: () =>
        runtime.setShowSessionEventsOnMap((current) => !current),
      onPrefetchVisibleMapArea: runtime.prefetchVisibleMapArea,
      onStartAddEditTrackpoint: controller.startAddEditTrackpoint,
      onRemoveSelectedEditTrackpoint: controller.removeSelectedEditTrackpoint,
      onSaveEditedSession: controller.saveEditedSession,
      onCancelEditSession: controller.cancelEditSession,
    },
    managementPanelProps: {
      safeHerds: data.safeHerds,
      selectedHerdId: session.selectedHerdId,
      selectedAnimalCount: session.sessionAnimalCount,
      sessionNotes: session.sessionNotes,
      currentSessionStatus: session.currentSessionStatus,
      isSaving: session.isSaving,
      isEventSaving: session.isEventSaving,
      eventNote: session.eventNote,
      eventStatus: session.eventStatus,
      actionError: session.actionError,
      safeCurrentTrackpointsLength: data.safeCurrentTrackpoints.length,
      currentMetrics: data.currentMetrics,
      safeCurrentSessionEvents: data.safeCurrentSessionEvents,
      onSelectedHerdIdChange: controller.changeSelectedHerdId,
      onAdjustAnimalCount: controller.adjustSessionAnimalCount,
      onSessionNotesChange: session.setSessionNotes,
      onStartSession: controller.startSession,
      onPauseSession: controller.pauseSession,
      onResumeSession: controller.resumeSession,
      onStopSession: controller.stopSession,
      onEventNoteChange: session.setEventNote,
      onAddSessionMarkerEvent: controller.addSessionMarkerEvent,
    },
    historyPanelProps: {
      isHistoryExpanded: history.isHistoryExpanded,
      safeRecentSessions: data.safeRecentSessions,
      safeHerds: data.safeHerds,
      safeSurveyAreas: data.safeSurveyAreas,
      selectedSurveyArea: data.selectedSurveyArea,
      selectedSurveyAreaId: selection.selectedSurveyAreaId,
      sessionHistoryStats: data.sessionHistoryStats,
      groupedSessionHistory: data.groupedSessionHistory,
      expandedHistoryDays: history.expandedHistoryDays,
      expandedHistorySessionId: history.expandedHistorySessionId,
      selectedSessionId: selection.selectedSessionId,
      selectedSession: data.selectedSession,
      selectedMetrics: data.selectedMetrics,
      safeSelectedTrackpoints: data.safeSelectedTrackpoints,
      safeSelectedSessionEvents: data.safeSelectedSessionEvents,
      editingSessionId: edit.editingSessionId,
      editMetrics: data.editMetrics,
      editTrackpointsLength: edit.editTrackpoints.length,
      editStartTime: edit.editStartTime,
      editEndTime: edit.editEndTime,
      actionError: session.actionError,
      isSaving: session.isSaving,
      onToggleHistoryExpanded: () => history.setIsHistoryExpanded((current) => !current),
      onToggleHistoryDay: controller.toggleHistoryDay,
      onExpandedHistorySessionChange: controller.toggleExpandedHistorySession,
      onFocusSurveyArea: runtime.focusSurveyArea,
      onSelectSession: selection.setSelectedSessionId,
      onStartEditSession: controller.startEditSession,
      onEditStartTimeChange: edit.setEditStartTime,
      onEditEndTimeChange: edit.setEditEndTime,
      onSaveEditedSession: controller.saveEditedSession,
      onCancelEditSession: controller.cancelEditSession,
      onDeleteSession: controller.deleteSession,
    },
  }
}
